name: Test
on: push
#   pull_request:                        # プルリクエストが作成されたら起動
#     paths: ['go/**/*.go']              # ただしGoのファイル変更時のみ
#   issues:
#     types: [opened, edited]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6      # ステップ1: チェックアウト 
      - uses: actions/setup-go@v6      # ステップ2: 言語セットアップ
        with:
          #go-version: '1.22'
          go-version-file: .go-version
      - run: go test go/excellent/*.go # ステップ3: テストの実行
